import localFont from "next/font/local";

export const RocGrotesk = localFont({
    src: [
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Black.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Bold.otf", weight: "700", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Black.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Bold.otf", weight: "700", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_ExtraBold.otf", weight: "800", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_ExtraLight.otf", weight: "200", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Heavy.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Light.otf", weight: "300", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Medium.otf", weight: "500", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed.otf", weight: "400", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Compressed_Thin.otf", weight: "100", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Black.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Bold.otf", weight: "700", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_ExtraBold.otf", weight: "800", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_ExtraLight.otf", weight: "200", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Heavy.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Light.otf", weight: "300", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Medium.otf", weight: "500", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed.otf", weight: "400", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Condensed_Thin.otf", weight: "100", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraBold.otf", weight: "800", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraLight.otf", weight: "200", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Black.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Bold.otf", weight: "700", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_ExtraBold.otf", weight: "800", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_ExtraLight.otf", weight: "200", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Heavy.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Light.otf", weight: "300", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Medium.otf", weight: "500", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide.otf", weight: "400", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_ExtraWide_Thin.otf", weight: "100", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Heavy.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Light.otf", weight: "300", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Medium.otf", weight: "500", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Regular.otf", weight: "400", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Thin.otf", weight: "100", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Variable_Compressed_Thin.otf", weight: "100", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Black.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Bold.otf", weight: "700", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_ExtraBold.otf", weight: "800", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_ExtraLight.otf", weight: "200", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Heavy.otf", weight: "900", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Light.otf", weight: "300", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Medium.otf", weight: "500", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide.otf", weight: "400", style: "normal" },
        { path: "../public/fonts/fonnts.com-Roc_Grotesk_Wide_Thin.otf", weight: "100", style: "normal" },
    ],
    variable: "--font-roc-grotesk",
    display: "swap",
});
